Fix for buildpack

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -39,32 +39,39 @@ install_node() {
   PATH=$BUILD_DIR/.vendor/node/bin:$PATH
 }
 
+# install_meteor() {
+#   if [ -f "$METEOR_HOME/usr/bin/meteor" ] ; then
+#     status "Skipping Meteor installation. Already installed."
+#     return
+#   fi
+
+#   # status "Install Meteor"
+#   # export PATH=/usr/bin:$PATH # necessary for install script to run from URL
+#   # curl https://install.meteor.com | sh
+#   status "Downloading Meteor install script"
+#   METEOR_INSTALL_SCRIPT=install_meteor.sh
+#   curl https://install.meteor.com?release=1.4.1.1/ > $METEOR_INSTALL_SCRIPT
+
+#   status "Installing Meteor connected to $MONGO_URL"
+#   sed -e '/^#!\/bin\/sh/ s/$/ -x/' \
+#     -e 's/set -/#set -/' \
+#     -e 's/curl --progress-bar --fail.*/curl "$TARBALL_URL" > meteor-bundle.tgz; tar -xzf meteor-bundle.tgz -C "$INSTALL_TMPDIR" -o/' \
+#     $METEOR_INSTALL_SCRIPT > install-meteor-verbose.sh
+#   chmod +x install-meteor-verbose.sh
+
+#   status "Execute ./install-meteor-verbose.sh"
+#   ./install-meteor-verbose.sh
+#   status "Done"
+
+#   status "Updating PATH with Meteor"
+#   PATH=$HOME/.meteor:$PATH
+# }
+
 install_meteor() {
-  if [ -f "$METEOR_HOME/usr/bin/meteor" ] ; then
-    status "Skipping Meteor installation. Already installed."
-    return
-  fi
-
-  # status "Install Meteor"
-  # export PATH=/usr/bin:$PATH # necessary for install script to run from URL
-  # curl https://install.meteor.com | sh
   status "Downloading Meteor install script"
-  METEOR_INSTALL_SCRIPT=install_meteor.sh
-  curl https://install.meteor.com?release=1.4.1.1/ > $METEOR_INSTALL_SCRIPT
-
-  status "Installing Meteor connected to $MONGO_URL"
-  sed -e '/^#!\/bin\/sh/ s/$/ -x/' \
-    -e 's/set -/#set -/' \
-    -e 's/curl --progress-bar --fail.*/curl "$TARBALL_URL" > meteor-bundle.tgz; tar -xzf meteor-bundle.tgz -C "$INSTALL_TMPDIR" -o/' \
-    $METEOR_INSTALL_SCRIPT > install-meteor-verbose.sh
-  chmod +x install-meteor-verbose.sh
-
-  status "Execute ./install-meteor-verbose.sh"
-  ./install-meteor-verbose.sh
-  status "Done"
-
-  status "Updating PATH with Meteor"
-  PATH=$HOME/.meteor:$PATH
+  curl -sL https://install.meteor.com?release=1.4.1.1 | sh
+  return_code $?
+   PATH=$HOME/.meteor:$PATH
 }
 
 build() {
